### PR TITLE
stdci: add integration with STDCI

### PR DESCRIPTION
**Pull request by fromanirh**
The goal is to run the functests, which in turn will
check for the KVM labels on real running OSes.
This complements, and does not supersedes, the existing unit tests.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
@MarSik @yanirq @ksimon1 
Here I'm exploring the STDCI integration using the KVM-info NFD plugins, which have really simple and cheap functional tests: just run the plugin and check the output againsta whitelist.

**Comment by yanirq** [comment]
I'm not sure k8s-1.11.0 is even needed any more unless you need to check for backward compatibility (I was thinking about deprecating it myself to align with kubevirt)

**Comment by fromanirh** [comment]
@yanirq no need for backward compat actually, so I'll remove it.

**Comment by fromanirh** [comment]
abandoned - can't work on this anymore

**Comment by fromanirh** [comment]
abandoned - can't work on this anymore

**Pull request closed without merging**
